name = "vollie"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"
send_metrics = true
# main = "src/workers.ts"

[[d1_databases]]
binding = "VOLLIE_DB"
database_name = "vollie-dev"
database_id = "a3810bf6-704d-45c4-bac3-a7097007c9d5"
migrations_dir = "drizzle/migrations"

[env.preview]
d1_databases = [
  { binding = "VOLLIE_DB", database_name = "vollie-dev", database_id = "a3810bf6-704d-45c4-bac3-a7097007c9d5" },
]

#[env.test]
#d1_databases = [
#  { binding = "VOLLIE_DB", database_name = "vollie-test", database_id = "331bcb84-2c8a-4063-88f8-36c647e629fd" },
#]

#[env.staging]
#d1_databases = [
#  { binding = "VOLLIE_DB", database_name = "vollie-staging", database_id = "b59b55f3-ce54-4330-a315-85a275acdc7f" },
#]